services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    env_file:
      - .env.localstack
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=ls-YEQOJiza-BidI-FoSI-1989-yuTeHoSi7c2d
    volumes:
      - ./scripts/localstack:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 25s
    networks:
      - network

volumes:
  localstack_data:
    driver: local

networks:
  network:
    driver: bridge
    name: network
